### PR TITLE
Add czech translate

### PR DESCRIPTION
**Pull request by filipsedivy**

### CODE REVIEW

**Comment by vgturtle127** [comment]
Could you close #12 please?

**Comment by vgturtle127** [comment]
You can re-open this issue, I just wanted you to close the other issue because there were two opened. Is the translation complete?

**Comment by filipsedivy** [comment]
I close this issue because the translate is complete.

**Comment by vgturtle127** [comment]
But were they merged into the main repository? Did you open a pull request?

**Comment by filipsedivy** [comment]
I can't reopen pull request beceuse i don't have permissions.

**Comment by vgturtle127** [comment]
OK, let me try to open a new PR.

**Comment by vgturtle127** [comment]
Oh, I see. The translation hasn't been commited at all yet. Now I understand.

**Pull request closed without merging**
